# Generated by Django 3.2.9 on 2021-11-04 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0003_rename_author_post_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
