# Generated by Django 3.2.9 on 2021-11-04 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0004_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
